### ISSUE TITLE
players.league is not a function

### ISSUE THREAD

**Issue by cheng1994** [whatadewitt/yahoo-fantasy-sports-api#88]
Attempting to use players.league but encountering a TypeError. Here's a full console ouput
```
 TypeError: app.yf.players.league is not a function
>      at /home/[computer]/Projects/server/functions/lib/index.js:90:43
>      at Layer.handle [as handle_request] (/home/[computer]/Projects/server/functions/node_modules/express/lib/router/layer.js:95:5)
>      at next (/home/[computer]/Projects/server/functions/node_modules/express/lib/router/route.js:137:13)
>      at Route.dispatch (/home/[computer]/Projects/server/functions/node_modules/express/lib/router/route.js:112:3)
>      at Layer.handle [as handle_request] (/home/[computer]/Projects/server/functions/node_modules/express/lib/router/layer.js:95:5)
>      at /home/[computer]/Projects/server/functions/node_modules/express/lib/router/index.js:281:22
>      at Function.process_params (/home/[computer]/Projects/server/functions/node_modules/express/lib/router/index.js:335:12)
>      at next (/home/[computer]/Projects/server/functions/node_modules/express/lib/router/index.js:275:10)
>      at cors (/home/[computer]/Projects/server/functions/node_modules/cors/lib/index.js:188:7)
>      at /home/[computer]/Projects/server/functions/node_modules/cors/lib/index.js:224:17
```

**Comment by whatadewitt** [comment]
On it!

**Comment by whatadewitt** [comment]
Wait a sec, you should be using `leagues` if you're using the `players` collceion

`players.leagues` should work! 

https://yahoo-fantasy-node-docs.vercel.app/collection/players/league
